version: '3.8'
services:
  db:
    env_file:
      ./backend/db.env
    image: postgres:14.1-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#  backend:
#    depends_on:
#      - db
#    env_file:
#      - ./backend/db.env
#    ports:
#      - '8080:8080'
#    build: ./backend


volumes:
  db:
    driver: local
