version: '3.8'
services:
  db:
    env_file:
      ./db.env
    image: postgres:14.1-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    env_file:
      - ./db.env
    volumes:
      - .m2:/root/.m2
    ports:
      - '8080:8080'
    build: ./


volumes:
  db:
    driver: local
